### ISSUE TITLE
do not show organization list anymore after organization was already chosen

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#286]
If you add and organization, the next time you add a new server, the list of organizations shouldn't be shown anymore, nor should you be allowed to search it. 

The only way to select another organization at that point would be through the "Reset" under settings, #281

**Comment by dzolnai** [comment]
Fixed.

**Comment by fkooman** [comment]
The app still shows "Fetching organizations..." that is no longer necessary if the organization was already chosen before...

**Comment by dzolnai** [comment]
The loading text was still using the term 'organization' but it was just the server list :) Fixed.
